### ISSUE TITLE
String Functions should operate on wchar_t instead of char

### ISSUE THREAD

**Issue by stevvooe** [sunlightlabs/jellyfish#1]
First, I'd like to say that this library is awesome. It has all the greats in one place and doesn't try to do anything too fancy. The implementations are clean as well.

Currently, the library doesn't really have support for unicode strings. If I try to submit a unicode string with a non-ascii character, I get a traceback:

    >>> jellyfish.hamming_distance(u'\u725b'.encode('utf8'), u'\u4faf')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    UnicodeEncodeError: 'ascii' codec can't encode character u'\u4faf' in position 0: ordinal not in range(128)

In addition, when one does encode them so that they will appropriately convert to an encoded string (non UCS-4 unicode), the incorrect answer is given. This example should give 1, rather than 3:

    >>> jellyfish.hamming_distance(u'\u725b'.encode('utf8'), u'\u4faf'.encode('utf8'))
    3

This obviously doesn't make sense for things like soundex or other english only algorithms, but as a general rule, python libraries should take only unicode objects for string operations.

Patching this library to support unicode objects, rather than string objects shouldn't be too bad. You just need to replace the PyString_FromString with PyUnicode_FromWideChar and update the functions to use wchar_t. Here is the python c api unicode reference:

http://docs.python.org/c-api/unicode.html

If you want, I can fork this and send you a pull request. Just let me know.

**Comment by jamesturk** [comment]
For posterity:

Jellyfish 0.5 makes the decision to use Unicode on all strings.  Given the shift to Python 3 this felt like the right thing to do, and while there will certainly be quite a few edge cases as discussed above, Python 3.4 representing all strings as wchar_t hopefully takes care of some of the major objections.

Some bugs may not be practical to fix on Python 2, so I'd expect as issues arise Jellyfish may start treating Python 2 as a second class citizen, and I'd venture a guess that whatever form it takes Jellyfish 1.0 will not have official support for Python 2.
