### ISSUE TITLE
stdbool.h issue during setup (Windows)

### ISSUE THREAD

**Issue by jgentes** [sunlightlabs/jellyfish#17]
Hey guys, I don't expect Windows to be a priority, but C99 isn't supported with visual studio any more, and the install of Jellyfish hits this error:

jellyfish-master\cjellyfish\jellyfish.h(4) : fatal error C1083: Cannot open include file: 'stdbool.h': No such file or directory

There's a lot of info out there to workaround this issue, but maybe you've already solved it?

Thanks,

-James

**Comment by pommedeterresautee** [comment]
I have the same issue. One possible solution would be to provide an already compiled version like it is done here for other compiled modules : http://www.lfd.uci.edu/~gohlke/pythonlibs/

**Comment by jamesturk** [comment]
I'd be glad to upload a prebuild windows binary to PyPI if someone can provide one.  I don't have a Windows build environment however

**Comment by jamesturk** [comment]
this is now fixed!  AppVeyor proved very useful.  let me know if you have any issues
