### ISSUE TITLE
string encoding parameter

### ISSUE THREAD

**Issue by macks22** [sunlightlabs/jellyfish#24]
If textual data is normally handled in Unicode, it must first be encoded in utf-8 format in order to ensure avoidance of `UnicodeEncodeError` during string comparisons. In particular, for the `jaro_winkler` string comparison:

    import jellyfish
    name = u'Francisco Alarc\xben'
    similarity = jellyfish.jaro_winkler(name, name)
    ---------------------------------------------------------------------------
    UnicodeEncodeError                        Traceback (most recent call last)
    <ipython-input-48-c671ac4ac12e> in <module>()
    ----> 1 jellyfish.jaro_winkler(p.full_name, p.full_name)

    UnicodeEncodeError: 'ascii' codec can't encode character u'\xbe' in position 15:     ordinal not in range(128)

This can be avoided by first encoding in utf-8:

    name = name.encode('utf-8')
    similarity = jellyfish.jaro_winkler(name, name)

... but it would be nice to have an option for this instead:

    similarity = jellyfish.jaro_winkler(name, name, 'utf-8')

**Comment by jamesturk** [comment]
adding a string encoding parameter to each function seems less than optimal to me right now, but it shouldn't error out if an encoding isn't provided.  revisiting how jf handles unicode is definitely on the agenda

**Comment by ar667** [comment]
Hi there,

Just to let you know that I get a "Segmentation fault: 11" in Python 3.4 when using the Damerau_Lev metric on strings that have Unicode characters such as "ȝ" but not "é".
