### ISSUE TITLE
exception IndexError

### ISSUE THREAD

**Issue by asafibe** [sunlightlabs/jellyfish#29]
try input: 
name1='Pedro Pablo Valdeben Petersen'
name2='Pedro Pablo Valdebenito Petersen'

**Comment by jamesturk** [comment]
which matching algorithm are you using?

**Comment by asafibe** [comment]
jaro_winkler

**Comment by jamesturk** [comment]
What version of jellyfish and what version of Python?  I'm unable to
reproduce this error with 0.3.3

On Tue, Jan 6, 2015 at 2:18 AM, Asaf Ben Ner <notifications@github.com>
wrote:

> jaro_winkler
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sunlightlabs/jellyfish/issues/29#issuecomment-68834069>
> .
>



-- 

James Turk
Labs Director | Sunlight Foundation <http://www.sunlightfoundation.com/>
202-558-8723 | @JamesTurk <https://twitter.com/jamesturk>

[image: Sunlight Foundation] <http://sunlightfoundation.com/>

**Comment by jamesturk** [comment]
closing this, please reopen w/ more info if it persists
