### ISSUE TITLE
Can you create a stand-alone repo for cjellyfish?

### ISSUE THREAD

**Issue by gihnius** [sunlightlabs/jellyfish#35]
I am wrapping it in a ruby gem: https://github.com/gihnius/jellyfish 
please.

**Comment by jamesturk** [comment]
hm, in theory yeah, but there is still a bit of Python-specific stuff in there, and probably needs to be more to better handle Unicode (something I'd been working on lately)

I'd be fine #ifdefing that stuff out though, let me take a look in the next few days

**Comment by jamesturk** [comment]
also worth mentioning that the tests are already factored out if you want to use those

**Comment by jamesturk** [comment]
looked at this a bit more, I think the best way would be to have something like

#ifdef CPYTHON
#include "Python.h"
#define UNICODE_T Py_UNICODE
#endif 

etc.

but I know next to nothing about Ruby's C API, would you be able to provide the equivalent?

**Comment by jamesturk** [comment]
OK this is spun out now.  feel free to open issues/PRs there https://github.com/sunlightlabs/cjellyfish
