### ISSUE TITLE
damerau_levenshtein_distance returns error

### ISSUE THREAD

**Issue by CoreyAR** [sunlightlabs/jellyfish#36]
The damerau_levenshtein_distance method returns an error. A google search did not return any solutions. 
Thanks.

>>> jellyfish.damerau_levenshtein_distance('Pop Country', 'Country Pop')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: must be cannot convert raw buffers, not str

**Comment by jamesturk** [comment]
thanks for this, that's an unhelpful error message for sure, I'll take a look at this ASAP- though

**Comment by jamesturk** [comment]
It's been brought to my attention this will work with unicode, so if you convert your strings to unicode literals it should work.  I'll work on getting a better error message in, right now there are a few inconsistencies in how jellyfish handles unicode between functions that I'll iron out in an upcoming release.

**Comment by jamesturk** [comment]
fixed in source
